# Basic options
title: Introduction to MATLAB
short_name: intro-matlab
developers: [J Hollins]
description: An introduction and guide to using MATLAB.
n_sessions: 2
prereq: NA
url: https://jake31may.github.io/intro-to-matlab

# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:path/index.html
    sort_by: lesson

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page

# Build settings
theme: jekyll-theme-slate
